// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MyMovieCollection
{
	public partial class MyMoviesViewController : UITableViewController
	{
		public MyMoviesViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
