// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using MyMovieCollection.Model.TMDb;

namespace MyMovieCollection
{
	public partial class DetailViewController : UIViewController
	{
		public MovieResult SelectedMovie { get; set; }

		public DetailViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.Title = SelectedMovie.title;
		}
	}
}
