// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyMovieCollection
{
	public partial class MyMoviesViewController : UITableViewController
	{
		public MyMoviesViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
